name:                post-server
version:             0.1.0.0
github:              "githubuser/post-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/post-server#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- time
- bytestring
- text
- aeson
- http-types
- http-client-tls
- http-client
- HDBC
- HDBC-postgresql
- warp
- wai
- wai-conduit
- lifted-base
- scrypt
- uuid
- filepath

library:
  source-dirs: src

executables:
  post-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - post-server

tests:
  post-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - post-server
